spring:
  application:
    name: ai-architect

# Actuator Endpoints aktivieren
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

ollama:
  base-url: http://localhost:11434
  model-name: codellama:7b
  temperature: 0.9

info:
  app:
    name: ai-architect
    description: Artificial Intelligenz Application for Softwarearchitects